import { Track } from "../types/track.type";

const Albums = {
  "eous-anthems": {
    album_name: "Eous Anthems",
    album_cover: "/covers/eous-anthems.png",
    album_id: "eous-anthems",
  },
  "casual-savior": {
    album_name: "Casual Savior",
    album_cover: "/covers/casual-savior.png",
    album_id: "casual-savior",
  },
  "daily-loop": {
    album_name: "Daily Loop",
    album_cover: "/covers/daily-loop.png",
    album_id: "daily-loop",
  },
};

export const tracks: Track[] = [
  {
    title: "Tour Inferno",
    title_id: "tour-inferno",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/tour-inferno.mp3",
    ...Albums["casual-savior"],
  },
  {
    title: "Sword of Corruption",
    title_id: "sword-of-corruption",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/sword-of-corruption.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "60% Daily",
    title_id: "60-percent-daily",
    artist: "Catbang",
    artist_id: "catbang",
    source: "/musics/daily-loop-60-daily.mp3",
    ...Albums["daily-loop"],
  },

  {
    title: "Ballet Labyrinth (Day)",
    title_id: "ballet-labyrinth-day",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/ballet-labyrinth--day.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Ballet Labyrinth (Night)",
    title_id: "ballet-labyrinth-night",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/ballet-labyrinth--night.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Binary Leading Lady in Blue Breen",
    title_id: "binary-leading-lady",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/binary-leading-lady-in-blue-breen.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Bloom of Doom",
    title_id: "bloom-of-doom",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/bloom-of-doom.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Camelia Week Battle",
    title_id: "camelia-week-battle",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/camelia-week-battle.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Chaos Alpha",
    title_id: "chaos-alpha",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/chaos-alpha.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Chaos Beta",
    title_id: "chaos-beta",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/chaos-beta.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Chaos Delta",
    title_id: "chaos-delta",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/chaos-delta.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Chaos Gamma",
    title_id: "chaos-gamma",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/chaos-gamma.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "60% Daily (Copy)",
    title_id: "60-percent-daily-copy",
    artist: "Catbang",
    artist_id: "catbang",
    source: "/musics/daily-loop-60-daily copy.mp3",
    ...Albums["daily-loop"],
  },
  {
    title: "Dance of Death",
    title_id: "dance-of-death",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/dance-of-death.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Derailed Order (Day)",
    title_id: "derailed-order-day",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/derailed-order--day.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Derailed Order (Night)",
    title_id: "derailed-order-night",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/derailed-order--night.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Dusk in the Wilderness",
    title_id: "dusk-in-the-wilderness",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/dusk-in-the-wilderness.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Endless Construction (Day)",
    title_id: "endless-construction-day",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/endless-construction-day--day.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Endless Construction (Night)",
    title_id: "endless-construction-night",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/endless-construction-day--night.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Four Armed Sword",
    title_id: "four-armed-sword",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/four-armed-sword.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Long Live the King",
    title_id: "long-live-the-king",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/long-live-the-king.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Meow",
    title_id: "meow",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/meow.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Metal Chimera",
    title_id: "metal-chimera",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/metal-chimera.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Pride and Paranoia",
    title_id: "pride-and-paranoia",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/pride-and-paranoia.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Shnnnn~",
    title_id: "shnnnn",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/shnnnn~.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Small but Great",
    title_id: "small-but-great",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/small-but-great.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Soil of Disaster",
    title_id: "soil-of-disaster",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/soil-of-disaster.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Soldier on Mission",
    title_id: "soldier-on-mission",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/soldier-on-mission.mp3",
    ...Albums["eous-anthems"],
  },
  {
    title: "Wind of the Wild",
    title_id: "wind-of-the-wild",
    artist: "Bangblues",
    artist_id: "bangblues",
    source: "/musics/wind-of-the-wild.mp3",
    ...Albums["eous-anthems"],
  },
];
